import {BaseSeeder} from '@adonisjs/lucid/seeders'
import Question from '#models/question'

export default class QuestionCombSeeder extends BaseSeeder {
  public async run() {
    const englishQuestions = [
     " Where should the tractor be positioned when checking the supports after disconnecting the trailer?",
       " When driving behind another vehicle, under good driving conditions, you should allow at least one second between your truck and the vehicle in front of you for ____ every foot of your truck's length.",
  "  There are two things a driver can do to prevent a rollover: (1) Keep the load as close to the ground as possible, and (2)",
    "The vehicle's brake air leakage rate (engine off, brakes on) should not exceed one foot per minute.",
   " If you cannot make a turn without entering another lane, you should:",
     " The higher your truck's center of gravity is, the:",
   " If the air brake line disconnects while you are driving the tractor (head) and trailer, but the emergency line remains connected, what will happen immediately?",
     " The hoses between the tractor and trailer usually connect which of these?",
     " The driver connected the air brake lines to the trailer. What will happen when these lines are connected to an old trailer?",
     " The manual valve should be used for:",
    "When driving a tractor with two trailers, which of the valves should be closed on the last trailer:",
      "The emergency line is disconnected or split while you are driving, causing a loss of pressure.",
      "If the brake springs are not released when the trailer's air supply valve is pushed, you should:",
    "Trailers manufactured before 1975 and equipped with air brakes",
    "There are two things a driver can do to prevent a rollover: (1) Drive slowly through curves and (2)",
    "After connecting the air hoses and before backing the tractor under the trailer, you should:",
      "Which part of the master bolt should the jaw lock be closed?",
      "How much space should be allowed between the upper and lower fifth wheel after coupling (mounting)?",
      "The trailer's air supply valve has been pressed. You should not back the tractor under the trailer until the air system is fully loaded and the PSI is at:",
    "You have mounted the tractor onto the trailer and connected the air hoses. You should:",
      "You have mounted the tractor onto the trailer and reversed, but the tractor is not underneath it. What should you connect before reversing?",
      "A tractor with a trailer... requires the shortest stopping distance.",
      "After the trailer is mounted on the tractor, you should select a higher gear.",
      "You can supply air to the trailer's tanks by...",
    "There are two things a driver can do to avoid a rollover: (1) drive slowly around turns and (2)",
   " Why should you ensure that the fifth wheel surface is properly lubricated?",
     " Your emergency air line is broken or ruptured while driving. The loss of pressure will cause...",
    "When connecting the hose handles, press the two rubber seals together to a degree...",
    "Which of these statements is true?",
   "Why should you close the hose handles (or fake them) when the trailer is not towing?",
     " When backing up the tractor under a trailer, you must...",
    "After the trailer is coupled to the tractor, which position should the tractor control safety valve be positioned?",
     "The fifth wheel jack is not locked after the jaws are closed around the master bolt. This means...",
    "Which of the following is a cause for veering off-lane or swerving to take a wider path when turning?",
      "The trailer's steel supports have been raised and are resting on the tractor. Make sure...",
    "When uncoupling a loaded trailer, you must lower the trailer supports until...",
    "What happens if the air hoses are extended when connected to an old trailer?",
      "To stop a trailer from skidding, you must...",
    "The air hoses between the tractor and trailer are often colored to prevent them from tangling. The emergency line is... and the service line is...",
 "Trailers manufactured before 1975 and equipped with air brakes:",
      "The combined air leakage rate (engine off, brakes on) should not exceed... (PSI) units of pressure per minute.",
      "Comparing a truck to a bus, there are... things to check in a truck.",
      "When checking the emergency brakes on a trailer, which position should the tractor's control safety valve be in?",
   " In normal driving, some drivers use the manual valve before the brake pedal to prevent the tractor from colliding with the trailer it is towing. Which of the following statements is true?",
      "When checking that the trailer is securely coupled to the tractor, the trailer supports must be...",
    "The air and electrical hoses from the tractor to the trailer must be...",
    "You have a large leak in the air hose, and you are using the brake compressor. Brake air will escape and cause a sway.",
      "A tractor with a(n) ____ trailer requires the greatest amount of stopping distance.",
      "When preparing to back the tractor under the trailer, you must align the ____",
    "You should not back the tractor under the trailer until the air pressure system is fully engaged.",
      "After locking the main track in the fifth wheel, you should check that the two wheels are properly connected by:",
     "gently pulling the tractor forward with the trailer brakes engaged.",
      "The tractor is mounted on the trailer. Where should you place the trailer's iron supports before starting to drive?",
    "The fifth wheel jack safety joint is in place to complete the coupling.",
      "After supplying air to the trailer, check that the air hoses are properly aligned and that the trailer brakes are working. This is done through:",
      "by backing under the trailer make sure that:",
      "How should you test the tractor-trailer connection?",
      "The front trailer supports are raised while the trailer is coupled to the tractor. Make sure that:",
      "To unlock the fifth wheel, you must... lock the jack.",
     "The tractor's safety valve will close, and the trailer's emergency brakes will engage when there is a major brake hose leak.",
      "When pairing, the proper fifth wheel position is…",
"What gear should the tractor engine be in after uncoupling the trailer and checking the trailer mounts?",
      "When disconnecting the trailer, after shutting off the air supply to the trailer and locking the trailer brakes, you must…",
"You are driving a truck. When the trailer disconnects, this disconnects all the air hoses. You expect the trailer brakes to engage, and you also expect…"
    ]

    const arabicQuestions = [
      "أين يجب ان يكون الجرار عند فحص المسندين, بعد فصل المقطورة؟",
      "بينما انت تقود خلف سيارة اخري, في ظروف قيادة جيدة يجب ان تسمح بثانية واحدة  علي الاقل بين شاحنتك والسيارة التي امامك لكل.......قدم من طول شاحنتك.",
      "هناك امران يمكن للسائق القيام بهما لمنع الانقلاب, و هي: (1), إبقاء الحمولة أقرب ما يكون إلى الأرض و  (2):",
      "لا ينبغي أن يكون معدل تسرب هواء مكابح المركبة (المحرك متوقف، المكابح متوقفة) اكثر من......في الدقيقة.",
      "إن لم تتمكن من الانعطاف دون الدخول في حارة مرورية اخري، يجب عليك:",
      "كلما ارتفع مركز ثقل شاحنتك، كان:",
      "إذا انفصل خط مكابح الهواء أثناء قيادتك للجرار(الرأس) والمقطورة، لكن خط الطوارئ بقي متصلا، فماذا سيحدث على الفور ؟",
      "الخراطيم  بين الجرار والمقطورة عادة ما تربط أي من هذه",
      "قام السائق بتوصيل خطوط الهواء الي المقطورة, ماذا سوف يحدث عند توصيل هذه الخطوط بمقطورة قديمة؟",
      "ينبغي استخدام الصمام اليدوي لـ ",
      "عند قيادة جرار بمقطورتين، اي من الصمامات يجب اغلاقه في المقطورة الاخيرة:",
      "أنفصل خط الطوارئ أو انقسم اثناء قيادتك، ذلك سيؤدي فقدان الضغط إلي",
      "اذا لم يتم اطلاق النوابض المكابح اثناء دفع صمام امداد الهواء للمقطورة، فيجب عليك:",
      "المقطورات المصنعة قبل عام 1975 والمجهزة بفرامل الهواء",
      "هناك شيئين يمكن للسائق القيام بهم من اجل من الانقلاب هما:(1)القيادة ببطء علي المنعطفات و الثانية هي(2):",
      "بعد توصيل خراطيم الهواء وكلن قبل الرجوع بالجرار تحت المقطورة يجب عليك",
      "أي جزء من المسمار الرئيسي, يجب علي  قفل الفك ان يغلقه؟",
      "ما مقدار المساحة التي يجب السماح بها بين العجلة الخامسة العلوية والسفلية بعد الاقتران (التركيب) ",
      "لقد ضغط علي صمام امداد الهواء الخاص بالمقطورة، لا يجب عليك الرجوع بالجرار تحت المقطورة حتي يكون نظام الهواء بالكامل:",
      "انت تركب الجرار علي المقطورة، و قمت بتوصيل خراطيم الهواء، يجب عليك:",
      "انت تركب الجرار علي المقطورة وقمت بالرجوع إلي الخلف، ولكن الجرار ليس تحتها، ما الذي يجب عليك شبكه قبل الرجوع ؟",
      "جرار مع مقطورة........ تتطلب أقصر قدر من مسافة التوقف.",
      "بعد تركيب المقطورة علي الجرار، يجب عليك اختيار غيار أعلي بمقدار",
      "يمكنك تزويد خزانات المقطورة بالهواء عن طريق",
      "هناك شيئين يمكن للسائق القيام بهم من اجل تجنب الانقلاب, هما (1) القيادة ببطء عند المنعطفات و(2)",
      "لماذا يجب أن تكون متأكدًا من أن سطح العجلة الخامسة مشحم بالشكل المطلوب ؟",
      "خط هواء الطوارئ الخاص بك تعطل, او تمزق اثناء القيادة, فقدان الضغط سوف يتسبب في",
      "عند توصيل مقابض الخراطيم، اضغط على الختمين المطاطيتين بالنسبة بعضهما البعض بدرجة",
      "أي من هذه العبارات صحيح ؟",
      "لماذا يجب عليك اغلاق مقابض الخراطيم (او غلقهم بطريقة وهمية) اثناء عدم جر المقطورة",
      "عند الرجوع بالجرار تحت مقطورة، يجب عليك",
      "بعد اقتران المقطورة بالجرار، يجب وضع صمام حماية التحكم في الجرار في أي وضع؟",
      "لم يتم قفل رافعة العجلة الخامسة بعد إغلاق الفكين حول المسمار الرئيسي وهذا يعني ما يلي",
      "أي هذه الاختيارات الاتية يكون سبباً في الخروج عن الحارة المرورية أو الغش المروري لإتباع مسار اوسع عند الانعطاف؟",
      "تم رفع المساند الحديدية للمقطورة  واصبحت ترتكز على الجرار. تأكد من",
      "عندما تقوم بفك ارتباط مقطورة محملة، يجب عليك تنزيل مساند المقطورة حتى",
      "ماذا سيحدث إذا تم تمديد خراطيم الهواء عندما توصيلها بمقطورة قديمة؟",
      "لإيقاف انزلاق المقطورة، يجب عليك",
      "غالبًا ما يتم تلوين خراطيم الهواء بين الجرار والمقطورة لمنعها من الاختلاط. خط الطوارئ هو، خط الخدمة هو",
      "المقطورات المصنوعة قبل عام 1975 والمجهزة بفرامل الهواء:",
      "لا ينبغي أن يكون معدل تسرب الهواء المركبة (المحرك متوقف، الفرامل تعمل) أكثر من.......(PSI) وحدة ضغط في الدقيقة.",
      "بمقارنة شاحنة مع أوتوبيس، هناك......من الأشياء للفحص في الشاحنة",
      "عند فحص مكابح الطوارئ في المقطورة، يجب وضع صمام حماية التحكم في الجرار في أي وضع ؟",
      "في القيادة العادية، يستخدم بعض السائقين الصمام اليدوي قبل دواسة الفرامل لمنع تصادم الجرار بالمقطورة التي يجرها. أي من الجمل الأتية صحيح ؟",
      "أثناء التحقق مما إذا كانت المقطورة مقترنة بشكل آمن بالجرار، يجب أن تكون مساند المقطورة",
      "يجب أن تكون الخراطيم الهوائية والكهربائية من الجرار إلى المقطو",
      "لديك تسرب كبير في خرطوم الهواء، وانت ضاغط الفرامل. سيهرب هواء الفرامل ويسبب",
      "جرار مع مقطورة.........، تتطلب أكبر قدر من مسافة التوقف",
      "عندما تستعد للرجوع بالجرار تحت المقطورة يجب عليك محاذاة",
      "يجب ألا ترجع بالجرار تحت المقطورة حتى يكون نظام ضغط الهواء",
      "بعد قفل المسار الرئيسي داخل في العجلة الخامسة، يجب عليك التحقق من اتصالهما جيداً من خلال",
      "سحب الجرار للأمام برفق مع قفل فرامل المقطورة؟",
      "تم تركيب الجرار علي المقطورة، أين يجب أن تضع مساند المقطورة الحديدية قبل  البدء في القيادة",
      "مفصل الأمان لرافعة العجلة الخامسة..........لكي يكتمل الاقتران",
      "بعد تزويد المقطورة بالهواء، تأكد من صحة ترتيب خراطيم الهواء وأن مكابح المقطورة تعمل. يتم ذلك من خلال",
      "الرجوع تحت المقطورة، تأكد من",
      "كيف يجب ان تختبر درجة امان اتصال الجرار بالمقطورة؟",
      "تم رفع مساند المقطورة الأمامية و في نفس الوقت المقطورة مقترنة بالجرار. تأكد من",
      "لفتح العجلة الخامسة، يجب.......قفل الرافعة",
      "سيتم إغلاق صمام حماية الجرار، و سوف تعمل فرامل الطوارئ في المقطورة عندما يكون هناك تسرب رئيسي في خرطوم فرامل",
      "عند الاقتران، يكون الموضع المناسب للعجلة الخامسة هو",
      "ما هو الغيار الذي يجب أن يكون عليه محرك الجرار بعد فك اقتران المقطورة وفحص مساند المقطورة ؟",
      "عند فصل المقطورة، بعد إيقاف إمداد المقطورة بالهواء وقفل مكابح المقطورة، يجب عليك",
      "أنت تقود شاحنة ،عندما تنفصل المقطورة، يؤدي ذلك إلى فصل كل خراطيم الهواء . و توقعت أن تُفعل مكابح المقطورة و تتوقع ايضاً أن"
    ]


    if (englishQuestions.length !== arabicQuestions.length) {
      throw new Error("Mismatch between English and Arabic questions")
    }


    const questions = englishQuestions.map((text, i) => ({
      questionCate: "COMB",
      questionText: text,
      questionTextAr: arabicQuestions[i],
    }))

    // bulk insert
    await Question.createMany(questions)
    console.log(`Inserted ${questions.length} COMB questions.`)
  }
}
